### ISSUE TITLE
Show events in calendar views

### ISSUE THREAD

**Issue by Vierheller** [Vierheller/Organizer#1]
We need to develop the month and weekviews.

month view:
    - show events in list below when date is selected
    - show some dots or markers in calendar

week view:
    - show events in calendar... just need to fill listener

**Comment by Attix22** [comment]
default Android CalendarView does not support showing markers or coloring anything :-( 

There are two possibilities:
1. Create custom view which extends calendar view and overwrite the onDraw() method
2. Use a custom calendar view.

I'm investigating which of those is easier

**Comment by Attix22** [comment]
Customize the builtin CalendarView seems more complicated than using an existing CustomView:
https://github.com/square/android-times-square

Got it to work quite fast. Seems exactly like what we wanted.
(Blue today, green days with an active Event)
![image](https://cloud.githubusercontent.com/assets/15377336/19270959/e8728814-8fc2-11e6-9e66-d95767be6563.png)

**Comment by Vierheller** [comment]
Looks great

**Comment by Vierheller** [comment]
Can we shrink the height of the calendar ? Cause we wanted to show a list at the bottom

**Comment by Attix22** [comment]
That seems rather ugly, I'm not a layout guy. Seems like it has a minimum fixed size :-(

I'll not commit those changes, I think we should all have a look on it.
