### ISSUE TITLE
Organizer crashes when closing, reopening app and then switching to listfragment 

### ISSUE THREAD

**Issue by Vierheller** [Vierheller/Organizer#14]
This is a database problem. It wants to reference the list it got from Database, but database is already closed.

**Comment by Attix22** [comment]
That's something which should be possible to test via component testing. 
https://developer.android.com/studio/test/espresso-test-recorder.html

**Comment by Vierheller** [comment]
Issue should be fixed in this commit
f5ddec50283451c8cad77fa9712b145fd13d8bc8
