### ISSUE TITLE
Handling of category unclear

### ISSUE THREAD

**Issue by Attix22** [Vierheller/Organizer#21]

**Comment by Vierheller** [comment]
categories are hard-coded. there is a 1 to 1 relationship. 

Or do you mean handling inside UI?

**Comment by Attix22** [comment]
handling inside UI, there is nothing implemented for adding a category.
Shouldn't this be a 1 category has n events relation?

**Comment by gabkol** [comment]
users should also be able to create own categories...

**Comment by gabkol** [comment]
Do we need a default category or should may the category be empty?

**Comment by 2xCmet** [comment]
There is no way to delete the Categorieso or better, there is no way of telling which category gets deleted.
