### ISSUE TITLE
App crashes sometimes...

### ISSUE THREAD

**Issue by gabkol** [Vierheller/Organizer#22]
Sometimes my Android phone tells me "Organizer has been closed". This messages comes hours after my last use of the app. Maybe it needs too much memory in background after a long time..?

**Comment by gabkol** [comment]
10-17 23:00:47.574 22386 22386 E AndroidRuntime: FATAL EXCEPTION: main

10-17 23:00:47.574 22386 22386 E AndroidRuntime: Process: de.grau.organizer, PID: 22386

10-17 23:00:47.574 22386 22386 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate receiver io.realm.internal.network.NetworkStateReceiver: java.lang.ClassNotFoundException: Didn't find class "io.realm.internal.network.NetworkStateReceiver" on path: DexPathList[[zip file "/data/app/de.grau.organizer-2/base.apk"],nativeLibraryDirectories=[/data/app/de.grau.organizer-2/lib/arm, /data/app/de.grau.organizer-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2884)

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at android.app.ActivityThread.-wrap14(ActivityThread.java)

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:111)

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:207)

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5728)

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

10-17 23:00:47.574 22386 22386 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.internal.network.NetworkStateReceiver" on path: DexPathList[[zip file "/data/app/de.grau.organizer-2/base.apk"],nativeLibraryDirectories=[/data/app/de.grau.organizer-2/lib/arm, /data/app/de.grau.organizer-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2879)

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    ... 8 more

10-17 23:00:47.574 22386 22386 E AndroidRuntime:    Suppressed: java.lang.ClassNotFoundException: Didn't find class "io.realm.internal.network.NetworkStateReceiver" on path: DexPathList[[dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-support-annotations-24.2.1_4e2c39f9b9e83156976f8a45d389433040a631bd-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-realm-annotations-2.0.0_a94d85e56fa302fdc83879d677552efbd23d9f36-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-me.zhanghai.android.materialprogressbar-library-1.1.7_8d5d67cb13fd1c2747f41bf770630405f9add2e3-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-io.realm-realm-android-library-2.0.0_86372101a37b9ed0253ca7cd1910463b85df28a5-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-internal_impl-24.2.1_cf0f5b7d90653d4ff4c7cd4a47e25a415bcf73b0-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-internal_impl-24.2.1_bd85f402b83a5a99f41d5594b523a0503736f127-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-internal_impl-24.2.1_ae22ec89aa30ca4862a4696126d1c9205be8bc08-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-internal_impl-24.2.1_4c42d3d40cbeb46a06e0f148cbc4dc3988ab897c-classes.dex", dex file "/data/data/de.grau.organizer/files/instant-run/dex/slice-internal_impl-24.2.1_152b3b44ba7794cbe95973ece4b51c71b09a0b6b-classes.dex", dex file "/data/data

10-17 23:00:52.864 25530 25549 E FileSourceProxy: Open dupFd fail for file

**Comment by Attix22** [comment]
Should be fixed by updateing to Realm 2.02
https://github.com/realm/realm-java/issues/3521
