### ISSUE TITLE
Month view not showing events

### ISSUE THREAD

**Issue by yrave** [Vierheller/Organizer#41]
If you click on the very right of a month button then the button is selected but the list is not updated.
<img width="283" alt="bildschirmfoto 2016-10-26 um 10 31 12" src="https://cloud.githubusercontent.com/assets/15361836/19718822/578311f6-9b67-11e6-9ac6-76cbcb7cf00c.png">

**Comment by gabkol** [comment]
Can you try it again? Maybe my last commit fixed it..

**Comment by yrave** [comment]
Events that start at 00:00 are shown randomly.

**Comment by gabkol** [comment]
Seems that we have a failure in method public List<Event> getEvents(CalendarDay calDate) of the EventsManager class. It's a very strange problem....
