### ISSUE TITLE
Leading / Trailing zeros in TaskActivity

### ISSUE THREAD

**Issue by yrave** [Vierheller/Organizer#44]
<img width="279" alt="bildschirmfoto 2016-10-26 um 18 40 40" src="https://cloud.githubusercontent.com/assets/15361836/19735411/b97f1c62-9bab-11e6-83f3-330e3c6cf359.png">

**Comment by Attix22** [comment]
Seems like somebody is using Calendar.HOUR instead of HOUR_OF_DAY

**Comment by gabkol** [comment]
I think @2xCmet didn't know it

**Comment by 2xCmet** [comment]
Didnt used either.
But is now fixed.
