### ISSUE TITLE
Left and Right Arrow in Week View

### ISSUE THREAD

**Issue by yrave** [Vierheller/Organizer#47]
The pictures are way too big. Size of the button should stay the same but the pictures should be smaller!

**Comment by 2xCmet** [comment]
If you doesn't care that the pictures arent in the middle anymore then it is easy to fix.
If you do care, I don't think it is so easy to fix

**Comment by 2xCmet** [comment]
Changed Button to ImageButton, so that i can set a resource for the button without stretching it.
