### ISSUE TITLE
Search draws over the current view

### ISSUE THREAD

**Issue by 2xCmet** [Vierheller/Organizer#52]
After you search for an Item and close the ResultView the UnderlayingView is just drawn above the old one.

**Comment by Attix22** [comment]
I don't understand, please provide screenshot

**Comment by 2xCmet** [comment]
![image](https://cloud.githubusercontent.com/assets/17165042/19758233/7933fcc8-9c27-11e6-9a0d-d8c91ccef3ae.png)
This is the hirachyview after 4times searching.
As you see the TabActivity is drawn 4 times.

**Comment by Attix22** [comment]
Fixed it
