### ISSUE TITLE
How to differ between Todo and Event?

### ISSUE THREAD

**Issue by Vierheller** [Vierheller/Organizer#9]
1. Option:
   Maybe have an other slider activity for Editoractivity.
   User can then select Todo or Event at the top of the View just like in tabactivity. Have a fragment for event and an other for Todo. 
2. Option
   On/off switch
   Then change the ui in each case
3. Option
   Just select no end time if you want to have a Todo. .. 😂

But how can the system decide if the database object is event or Todo? ??

**Comment by gabkol** [comment]
Already solved
